### ISSUE TITLE
setup `babysuid` when using your src on my local server

### ISSUE THREAD

**Issue by hitfzyangdianshi** [pwncollege/pwncollege#21]
After I get the flag, the error is:  

`Error: this challenge is not correctly configured`
The error may be from here:https://github.com/pwncollege/pwncollege/blob/78268801eaa2c7a40f5d96decb7332af4c6c9bb9/CTFd_plugin/user_flag.py#L106

the flag is set as:
![image](https://user-images.githubusercontent.com/10493326/114523121-984a1d00-9c76-11eb-9b6c-07e3e7f33af8.png)

am I correct? or what should I do to fix this error?

**Comment by ConnorNelson** [comment]
Babysuid expects `multi` flags. Since babysuid requires users to specify a path to a binary, that path gets embedded into the flag. The `multi` flag takes care of the logic of checking this path.

**Comment by hitfzyangdianshi** [comment]
got it.  thanks
